apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-cert
  namespace: n8n
spec:
  secretName: n8n-tls-secret
  dnsNames:
  - n8n.winty.server
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer