apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-cert
  namespace: n8n
spec:
  secretName: n8n-tls
  dnsNames:
  - n8n.winty.cloud
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer